SELECT
    SHIPMENT_ID,
    ESTIMATED_DELIVERY_DATE,
    ACTUAL_DELIVERY_DATE,
    DELAY_REASON
FROM {{ source('silver_data', 'delivery_status') }}
WHERE ACTUAL_DELIVERY_DATE > ESTIMATED_DELIVERY_DATE