SELECT 
    CUSTOMER_ID,
    CONCAT(CUSTOMER_FIRST_NAME , ' ', CUSTOMER_LAST_NAME) CUSTOMER_NAME,
    SUM(REVENUE_GENERATED) TOTAL_REVENUE
FROM {{ source('silver_data', 'customers') }}
JOIN {{ source('silver_data', 'shipments') }} USING (CUSTOMER_ID)
GROUP BY 1, 2
ORDER BY TOTAL_REVENUE DESC
LIMIT 10